### ISSUE TITLE
ajax文件夹里文件怎么用？

### ISSUE THREAD

**Issue by Helloworld-zyt** [msdx/androiddoc#1]
需要在本地部署吗？还是什么都不需要做，自动识别的？

**Comment by msdx** [comment]
clone下来直接打开docs里面的index.html就行。都是静态文件。adax里的文件你不用管，我已经把它上传到我的七牛空间了，docs里面用到的外部文件都是指向360镜像库和我空间上的。

**Comment by msdx** [comment]
下次更新可能会把它们放在同一个目录下。克隆到本地就使用本地的。

**Comment by msdx** [comment]
已更新，ajax已包含在docs中。

**Comment by Helloworld-zyt** [comment]
thanks
