### ISSUE TITLE
DNS Error

### ISSUE THREAD

**Issue by hunter524** [msdx/androiddoc#2]
无法正常访问了。

**Comment by msdx** [comment]
O.O我这里正常。。
这个是托管在七牛空间的，如果是DNS解析错误的话是不是你的DNS服务有问题？
试一下114.114.114.114的DNS？
昨晚更新了一下文档，可能CDN有些没有刷新。你试一下这个能不能正常打开：7ktv9b.com1.z0.glb.clouddn.com

**Comment by hunter524** [comment]
7ktv9b.com1.z0.glb.clouddn.com 访问ok！谢谢

**Comment by msdx** [comment]
@hunter524 我想可能是部分地区的CDN部分内容没刷新的情况，因为昨晚我更新了一下文档，早上也是有部分资源是打不开的，但过了一段时间后就正常了。
