### ISSUE TITLE
图片无法加载

### ISSUE THREAD

**Issue by pingpingpang001** [msdx/androiddoc#3]
http://msdx.github.io/androiddoc/docs/design/index.html
http://msdx.github.io/androiddoc/docs/develop/index.html
首页 下拉第二屏Build Beautiful Apps版块加载不出来 Build for a Multi-Screen World 板块不能加载出来
最底下BlogSupport图片没出来，点击报404

http://msdx.github.io/androiddoc/docs/sdk/index.html  android studio下载链接会直接到官网的tools页面

**Comment by msdx** [comment]
它对图片的引用使用的是`/xxx/xxx/xxx.png`这样的路径，在msdx.github.io/androiddoc中因为有`androiddoc/doc`这样的子目录的问题，导致对应的路径不对……
刚才看了一下，约有141672处引用都是这样用的。看来只能先使用部署在七牛空间上的。。。

**Comment by msdx** [comment]
已修复。

**Comment by msdx** [comment]
4e979325586b00cff5a0dc664f3f792d7847bf4b 修复部分路径替换有误的问题。
