### ISSUE TITLE
好久没更新了, 很多东西都没有

### ISSUE THREAD

**Issue by imknown** [msdx/androiddoc#4]
比如说 官方的 Sample , Android N Preview 等..

**Comment by msdx** [comment]
N Preview待下次到公司更新，家里的windows在批量处理文本上有些弱。内容是和sdk里下载的doc一样的，你说的没有sample，是android N Preview里的内容吗？

**Comment by imknown** [comment]
![image](https://cloud.githubusercontent.com/assets/5681447/13722892/023e8f44-e88f-11e5-9ba2-363b3995a961.png)

是这些, 你的这个七牛, 应该是 右上角的搜索的JS好使的, 全网最新的 网站了, 非常感谢.

**Comment by msdx** [comment]
七牛每个月有免费的限额流量，并且速度比较快，所以我部署到了七牛。
右上角的搜索，在sdk里下的doc都是有的。不过我们下载的doc，由于里面有大量被墙的链接，所以导致打开缓慢。你也可以把本项目clone或下载到电脑上，本地使用。
如果你是使用linux/mac的话，也可以自己更新Android N Preview的文档之后进行处理来提高打开速度。

**Comment by imknown** [comment]
我脱机的文档 不上 vpn, js 等内容根本不好用, 还不如上 `dev.android.com`, 你的这个托管的, 非常实用. 已在公司推广.

**Comment by msdx** [comment]
客气了，能用就好。

**Comment by imknown** [comment]
嗯 谢谢 不麻烦你们了, 我们自己研究研究, 谢谢 :laughing:

**Comment by msdx** [comment]
客气了。这项目目前其实也就我一个人在维护，其实也只是用一些命令或脚本，自己把所有的html及js代码中涉及到google的链接都给过滤掉，并且把剩下的引用到了墙外的图片或页面给下载下来，把相关的链接替换为下载的页面。
目前里的ajax就是引用到的墙外非`dev.android.com`的资源，`handleabspath.groovy`是进行相对路径处理的groovy脚本，`pathtool`是写的一个计算相对路径的可执行文件，`handledocs`和`handleajax`都是进行替换的shell脚本。

**Comment by imknown** [comment]
哈~ 谢谢点拨~ 我小白一枚, 我自己谷歌谷歌 研究研究.

**Comment by msdx** [comment]
你好，我刚看了一下，N Preview的文档还没有出来吧。

**Comment by imknown** [comment]
是的, SDK 文档至少还等几个月, 现在真的是 preview ...

**Comment by msdx** [comment]
@imknown [http://msdx.github.io/androiddoc/docs/](#)的访问地址已经更新至Android N Developer Preview 1，不过我看了一下官方提供下载的这个文档，内容比6.0少了一半，许多东西都没有，基本只剩下api的内容，可以查询23到N的API变化。由于文档完整度较低，故部署在七牛空间的文档暂不更新。N（或N Preview）的完整文档估计得等sdk更新。

**Comment by imknown** [comment]
哇!! 谢谢!! 辛苦了!!
