### ISSUE TITLE
现在最新的7.0 API 为什么搜索功能用不了呢？

### ISSUE THREAD

**Issue by jutao** [msdx/androiddoc#5]

**Comment by imknown** [comment]
:D 貌似是该更新了~

**Comment by msdx** [comment]
应该是被我意外过滤掉了。

刚收到群友煎饼同学的消息，目前墙内可访问：https://developer.android.google.cn 。
此项目将停止维护。

**Comment by imknown** [comment]
目前 不能在线搜索, 只能浏览, 这是一个悲伤的故事.

**Comment by msdx** [comment]
官方提供的站点可以搜索api
